# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
                root_url: "//%env(SITE_BASE_HOST)%%articles_uploads_url%"
                cache_prefix: media/cache
                visibility: public
        img_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.img_filesystem
                root_url: "//%env(SITE_BASE_HOST)%%img_url%"
                cache_prefix: media/cache
                visibility: public

    loaders:
        articles_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
        img_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.img_filesystem
    data_loader: articles_flysystem_loader

    filter_sets:
        cache: ~

        avatar_img:
            quality: 75
            filters:
                thumbnail: { size: [ 500, 500 ], mode: outbound }
        article_image:
            quality: 75
            filters:
                thumbnail: { size: [ 500, 500 ], mode: outbound }